FROM tomcat:8.0 AS tomcat8


RUN apt-get update && apt-get -y upgrade
RUN apt-get update \
&& apt-get install -y \
        nmap \
        vim

WORKDIR /usr/local/tomcat

COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml

EXPOSE 9090



